name: Suicide
version: ${project.version}
main: me.prism3.suicide.Main
api-version: 1.13
authors: [ Prism3 ]
description: Simple suicide command with some cool features
commands:
  suicide:
    description: Suicide command
    aliases:
    - killme
  suicide reload:
    description: Reload the plugin config
permissions:
  suicide.command:
    description: "Suicide command"
    default: true
  suicide.bypass:
    description: "Bypass the cooldown"
    default: op
  suicide.reload:
    description: "Reload the plugin config"
    default: op
